version: '3.8'

services:
  pucmm_eict_github_invitations:
    container_name: pucmm_eict_github_invitations
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8089:8080"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      pucmm_eict_github_invitations:

networks:
  pucmm_eict_github_invitations:
    external: true
    name: pucmm_eict_github_invitations
