pucmm:
  features:
    send-email-notification: ${PUCMM_SEND_EMAIL_NOTIFICATION}
  rate-limit: ${RATE_LIMIT}
  cache-in-seconds: ${CACHE_IN_SECONDS}
  github-org: ${PUCMM_GITHUB_ORGANIZATION}
  emails: ${PUCMM_EMAILS:}
  send-to-email: ${PUCMM_SEND_TO_EMAIL}
  subjects:
    st-icc-354:
      name: ${PROGRAMACION_WEB_AVANZADA_TEAM_LABEL}
      github-team: ${PROGRAMACION_WEB_AVANZADA_TEAM}
      google-spread-sheet-id: ${PROGRAMACION_WEB_AVANZADA_SPREADSHEET_ID}
      pva-current-id: ${PROGRAMACION_WEB_AVANZADA_PUCMM_PVA_CURRENT_ID}
      spread-sheet-range: ${PROGRAMACION_WEB_AVANZADA_SPREADSHEET_RANGE}

google:
  service-account-id: ${GOOGLE_SERVICE_ACCOUNT_ID}
  application-name: "Web Application"
  service-account-json-file-location: ${GOOGLE_SERVICE_ACCOUNT_JSON_FILE_LOCATION}

debug: false

logging:
  level:
    feign: ${LOG_LEVEL_EDU_PUCMM:info}
    edu:
      pucmm: ${LOG_LEVEL_EDU_PUCMM:info}

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator

server:
  port: ${SERVER_PORT:8080}

spring:
  mail:
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: false
          starttls:
            enable: true
          transport:
            protocol: smtp
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    default-encoding: UTF-8
    protocol: smtp
    test-connection: true

  application:
    name: Pucmm Github Invitations
    admin:
      enabled: false
  web:
    resources:
      static-locations: classpath:/static/
  profiles:
    active: ${SPRING_PROFILE:local}
    default: local
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl

